/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.capg;

public class StateCensusAnalyser {
  // private static final String CSV_FILE_LOCATION = ""; 
	public static void main(String[] args) {
		System.out.println("Welocome to Indian State Census Analyzer");
	}        
}
